# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('/content/RBI VS CPI.csv')
print(df.head())
print(df.columns.tolist())

df.columns = df.columns.str.strip()

correlation = df['YOY inflation %'].corr(df['Repo Rate (%)'])
print(f"Pearson Correlation: {round(correlation, 4)}")

for lag in [3, 6, 12]:
    lagged = df['YOY inflation %'].shift(-lag).corr(df['Repo Rate (%)'])
    print(f"Correlation at {lag}-month lag: {round(lagged, 4)}")

lags = [0, 3, 6, 12]
correlations = [-0.1774, -0.1804, -0.1939, -0.2592]

plt.figure(figsize=(8,5))
plt.bar(lags, correlations, color='steelblue', width=2)
plt.axhline(0, color='black', linewidth=0.8)
plt.title('Repo Rate vs Inflation: Correlation at Different Lags')
plt.xlabel('Lag (Months)')
plt.ylabel('Pearson Correlation Coefficient')
plt.xticks(lags)
plt.tight_layout()
plt.savefig('lag_correlation.png')
plt.show()
print("Chart saved")